spring:
  profiles:
    active:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url:
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql : true
        default_batch_fetch_size: 1000

    show-sql: true
    open-in-view: false

cloud:
  aws:
    s3:
      bucket: unimeet-bucket
    stack:
      auto: false
    region:
      static: ap-northeast-2
      auto: false
    credentials:
      access-key:
      secret-key:

com:
  amazonaws:
    sdk:
      disableEc2Metadata: true

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

default:
  profile:
    image:
      url: